### ISSUE TITLE
[Site] Add Intel logo to contributors section of website

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#166]
**Current Behavior**
Individuals at Intel have joined the Service Mesh Performance initiative.

**Desired Behavior**
Intel's participation should be represented in the Contributors section of the website.

**Comment by BondaSaim** [comment]
May I have this task @leecalcote ?

**Comment by leecalcote** [comment]
@BondaSaim Thank you for volunteering. Yes.
