### ISSUE TITLE
[Site] Add SolarWinds Logo

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#170]
**Current Behavior**
Individuals at SolarWinds have contributed the Service Mesh Performance initiative.

**Desired Behavior**
SolarWinds' participation should be represented in the Contributors section of the website.

Find a copy of the SolarWinds logo on the https://meshery.io site.

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@PluckyPrecious @Ruth-ikegah @Abiola-Farounbi @Anita-ihuman .... any takers here?

**Comment by PluckyPrecious** [comment]
Sure.👍🏽

**Comment by leecalcote** [comment]
Opening back up for assignment (feel free to grab this one again, @PluckyPrecious, if you've time).

**Comment by xdshivani** [comment]
Assign this to me

**Comment by leecalcote** [comment]
Thank you, @xdshivani. 👍

**Comment by xdshivani** [comment]
Help me installing meshery.io in my system `windows10` environment. As am getting error while installing 
![code](https://user-images.githubusercontent.com/56837749/113481299-5f5fba80-94b6-11eb-836d-b5e0b5566f51.PNG)

**Comment by leecalcote** [comment]
Contributors within the Layer5 community I have created a few resources for Windows users and Jekyll. I encourage you to in the community - http://slack.layer5.io - and inquire inside. More info- https://layer5.io/community

**Comment by leecalcote** [comment]
@PluckyPrecious @Anita-ihuman @Ruth-ikegah I wonder if we have these instructions centralized.

**Comment by PluckyPrecious** [comment]
Hello @xdshivani you can find instruction [here](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#set-up-your-development-environment) on how to run Jekyll on windows

**Comment by Anita-ihuman** [comment]
This information is in the Newcomers doc

https://docs.google.com/document/u/0/d/1aHarIyIL__HRq_4klYOUsEXP5SQLlmb50W17yKdNmpU/mobilebasic

**Comment by theprogrammedwords** [comment]
Is there any update on this? @xdshivani , or do you need some help ?

**Comment by Jashpatel1** [comment]
@xdshivani Any updates here?

**Comment by warunicorn19** [comment]
@soham4abc are you working on this?

**Comment by soham4abc** [comment]
> @soham4abc are you working on this?

No I am not

**Comment by soham4abc** [comment]
> > @soham4abc are you working on this?
> 
> No I am not working on this issue anymore
