### ISSUE TITLE
GitHub Action to run SMP performance tests

### ISSUE THREAD

**Issue by navendu-pottekkat** [service-mesh-performance/service-mesh-performance#184]
**Current Behavior**
Meshery provides a general purpose implementation of Service Mesh Performance (SMP). Performance tests can be invoked from either of Meshery's two clients: the UI or CLI. 

`mesheryctl perf` command runs SMP-compatible performance tests.

**Desired Behavior**

A GitHub Action/Workflow should be created that leverages this command to run performance tests, so that users and service mesh projects alike can incorporate these performance tests into their pipelines.

**Comment by leecalcote** [comment]
@ramrodo this would be fantastic to have as it will facilitate each service mesh project team to incorporate Meshery and its compliance tests into their CI system (assuming GitHub in this case).

**Comment by ramrodo** [comment]
@navendu-pottekkat could you assign this issue to @s1ntaxe770r, I don't know why I can not do it.

**Comment by leecalcote** [comment]
When the action is ready, a workflow that uses it can be built into each Meshery Adapter repo.

**Comment by DelusionalOptimist** [comment]
Yes, very soon : )

**Comment by iambami** [comment]
@navendu-pottekkat I think this issue is solved, can it be closed?

**Comment by navendu-pottekkat** [comment]
Thank you for pointing this out @iambami !

How far have we come since April!

Meshery SMP Action: https://github.com/layer5io/meshery-smp-action
