### ISSUE TITLE
[Site] Mailing Lists: Add mailing list sign up to site

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#205]
**Current State of the service-mesh-performance site**
SMP's mailing list and newsletter is not publicly available.

**Desired State of the service-mesh-performance site**
Similar to the Meshery site, the smp-spec.io site should have a newsletter sign-up and  the following mailing lists:

 - community@smp-spec.io - a form-based sign-up; open for anyone to signup for news / update on the project and service mesh topics in general.
 - user-group@smp-spec.io - a link to the google group; open for anyone to join.
 - maintainers@smp-spec.io - a link to the email address; open for anyone to send an email to.

**Comment by leecalcote** [comment]
@Neilblaze or @NikhilSharma03, would either of you like to take this one?

**Comment by NikhilSharma03** [comment]
@leecalcote Just to get a clear understanding of the issue:
The desired output should be something like.
## Newsletter sign up

The current page has this signup form

![Screenshot from 2021-06-30 11-24-19](https://user-images.githubusercontent.com/58226527/123909002-0957c180-d996-11eb-8b4e-63b0d6399fc7.png)

## Mailing List

As in the meshery
![Screenshot from 2021-06-30 11-19-18](https://user-images.githubusercontent.com/58226527/123908509-3d7eb280-d995-11eb-9fb0-5e3c44b0ae58.png)

** We can add three buttons **
- Community - which links to mailto:community@smp-spec.io
- User Group - which links to mailto:user-group@smp-spec.io
- Maintainer - which links to mailto:maintainers@smp-spec.io

**Comment by leecalcote** [comment]
@NikhilSharma03 close. user-group@smp-spec.io - should be a link to the google group;

**Comment by leecalcote** [comment]
@NikhilSharma03 @Jashpatel1, it seems that I have neglected to include links to the google groups themselves. 

- https://groups.google.com/a/smp-spec.io/g/community
- https://groups.google.com/a/smp-spec.io/g/user-group
- https://groups.google.com/a/smp-spec.io/g/maintainers
