### ISSUE TITLE
Footer not mobile friendly

### ISSUE THREAD

**Issue by warunicorn19** [service-mesh-performance/service-mesh-performance#214]
**Description**
The footer on the SMP website is not mobile friendly.

**Expected Behavior**
At a certain screen size the text in the footer gets overlapped with the logo.

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by debo19** [comment]
@warunicorn19  Can I work on this?

**Comment by warunicorn19** [comment]
yup! @debo19
