### ISSUE TITLE
[Site] Responsive Issues in CN Section

### ISSUE THREAD

**Issue by NikhilSharma03** [service-mesh-performance/service-mesh-performance#217]
**Description**
- The Cloud Native section is not responsive for smaller screens.

**Expected Behavior**
- Fix the responsiveness of the CN section.

**Screenshots**
![Screenshot from 2021-07-23 18-19-47](https://user-images.githubusercontent.com/58226527/126784191-214cf174-a5d2-4f68-b414-6cb9877c3162.png)

**Environment:**
 - OS: [Ubuntu]
 - Browser: [Chrome]

**Comment by NikhilSharma03** [comment]
## Note
- I would love to work on this issue.

**Comment by sayantan1413** [comment]
Great @NikhilSharma03 🎉

**Comment by warunicorn19** [comment]
hey @NikhilSharma03 my recent PR fixes this issue.

**Comment by NikhilSharma03** [comment]
> hey @NikhilSharma03 my recent PR fixes this issue.

Awesome. I will close this issue then.
