### ISSUE TITLE
Make the Layer5 a clickable link

### ISSUE THREAD

**Issue by Anita-ihuman** [service-mesh-performance/service-mesh-performance#218]
**Description**
Currently, Layer5 logo in this section is not a clickable link.

**Expected Behavior**
Add a link to the Layer5 logo directing to the Layer5.io website

**Screenshots**
![Screenshot 2021-07-23 at 12 00 19](https://user-images.githubusercontent.com/62384659/126809459-3bb3e671-2c00-461f-a140-81de5b9ba09f.png)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by warunicorn19** [comment]
hey @Anita-ihuman , i already fixed this in my recent PR

**Comment by kumarshobhit** [comment]
Can I work on this issue @warunicorn19 if you have not merged your changes yet?

**Comment by warunicorn19** [comment]
@kumarshobhit that'll cause a conflict, since its already a part of an existing PR waiting to get merged, why dont you take a look at some other existing issues?

**Comment by kumarshobhit** [comment]
This issue was beginner-friendly so I thought it will be a good one to start contributing to the project. But yeah, I will surely look at other issues to solve.

**Comment by Anita-ihuman** [comment]
@kumarshobhit, apologies for the confusion.
It’s fine, there will be other friendly issues coming up.

**Comment by kumarshobhit** [comment]
yes noted.
