### ISSUE TITLE
[Site] Add reference to SMP Community Group

### ISSUE THREAD

**Issue by navendu-pottekkat** [service-mesh-performance/service-mesh-performance#221]
**Current State of the service-mesh-performance site**
SMP has a new [Community Group](https://community.cncf.io/service-mesh-performance-community/) in Cloud Native Community Groups.

**Desired State of the service-mesh-performance site**
A reference to join this group should be added to the SMP website.

Community Group URL: https://community.cncf.io/service-mesh-performance-community/

**Comment by soham4abc** [comment]
I would like to work on this issue! Where do you want me to put the reference of the community group?

**Comment by navendu-pottekkat** [comment]
Sure @soham4abc , I had added reference to the meeting to the website. But that was a quick fix. Maybe we can change it up a bit. @leecalcote could you suggest changes to the current website?

**Comment by soham4abc** [comment]
> Sure @soham4abc , I had added reference to the meeting to the website. But that was a quick fix. Maybe we can change it up a bit. @leecalcote could you suggest changes to the current website?

Once he suggests I should start working on it!

**Comment by navendu-pottekkat** [comment]
Sure, thank you. You can check if you can find a better place to add the meeting details. It is here now:

![Screenshot 2021-08-11 at 3 25 33 PM](https://user-images.githubusercontent.com/49474499/129009429-c3aaad90-2513-4dba-be15-ee15c2394b75.png)

**Comment by soham4abc** [comment]
> Sure, thank you. You can check if you can find a better place to add the meeting details. It is here now:
> 
> ![Screenshot 2021-08-11 at 3 25 33 PM](https://user-images.githubusercontent.com/49474499/129009429-c3aaad90-2513-4dba-be15-ee15c2394b75.png)

URL to the site would be very helpful
