### ISSUE TITLE
IEEE Bridge article for SMP

### ISSUE THREAD

**Issue by navendu-pottekkat** [service-mesh-performance/service-mesh-performance#223]
**Desired Behavior**

A draft of the article for IEEE Bridge needs to be delivered. [Link to abstract](https://docs.google.com/document/d/1tv3VFzn1fVKLwGPUnKs6I6zp-ZTYpOxy1BeC-3ivzeU/edit#heading=h.96avnrd4ywp2).

**Comment by leecalcote** [comment]
First draft completed and submitted for review.

**Comment by leecalcote** [comment]
Link to draft - https://docs.google.com/document/d/1tv3VFzn1fVKLwGPUnKs6I6zp-ZTYpOxy1BeC-3ivzeU/edit#

**Comment by sunkuranganath** [comment]
Looking forward to the publication

**Comment by leecalcote** [comment]
Publisher's review is complete. Suggested edits forthcoming.

**Comment by leecalcote** [comment]
Published! https://www.nxtbook.com/nxtbooks/ieee/bridge_issue3_2021/index.php#/p/16  // @sunkuranganath @mum4k @mganguli @oschaaf
