### ISSUE TITLE
[Site] Add hyperlink to slide deck 

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#228]
**Current State of the service-mesh-performance site**
The project overview deck is iframe'd on the main project page - https://smp-spec.io
Visitors that want direct access to the presentation, though, aren't provided a link to the presentation.

**Desired State of the service-mesh-performance site**
Add a [hyperlink to the deck](https://docs.google.com/presentation/d/1fm7Eu1T3JSBPVmdFYyyevqQLSmAMLXqzWqC7QxTHGX8/edit#) underneath the iframe'd display of the deck.

**Comment by leecalcote** [comment]
@soham4abc ... you might tackle this one...

**Comment by soham4abc** [comment]
> @soham4abc ... you might tackle this one...

Okay I am on it!
