### ISSUE TITLE
[Chore] Contributing instructions update

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#229]
Update the CONTRIBUTING.md to say that SMP prominently and consistently engages with the Meshery project. For a more complete set of contributing guides see docs.meshery.io/project/contributing.

**Comment by ShivamTyagi12345** [comment]
Hey @leecalcote .Can I help with this

**Comment by Rishi22-Coding** [comment]
I'm working on this Issue
