### ISSUE TITLE
Add link to CNCF SMP Community 

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#238]
**Desired State of the service-mesh-performance site**
Find a good spot to add a link to the SMP Community as hosted on the CNCF Community site - https://community.cncf.io/service-mesh-performance-community/

**Comment by Rishi22-Coding** [comment]
I will try this. Please assign me this work

**Comment by warunicorn19** [comment]
Here you go! @Rishi22-Coding

**Comment by Rishi22-Coding** [comment]
@warunicorn19 Thank You

**Comment by warunicorn19** [comment]
@leecalcote we already have this link on the website right? 


![Screenshot_20210911-012153](https://user-images.githubusercontent.com/53532328/132909896-c0fd5918-27af-414f-834f-335cdd24d4e2.jpg)

**Comment by leecalcote** [comment]
@warunicorn19 yes, you're right. 👍
