### ISSUE TITLE
Incorporate screenshot into website

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#250]
**Current State of the service-mesh-performance site**
The site only has one screenshot of an SMP implementation.

**Desired State of the service-mesh-performance site**
Incorporate this screenshot of a performance test comparison into the site.

<img width="1605" alt="SMP comparisons in Meshery" src="https://user-images.githubusercontent.com/7570704/135864947-baf1c64b-d070-4fbf-a6c7-348e93924b34.png">

**Comment by leecalcote** [comment]
@adithyaakrishna would you like to finish this one off?

**Comment by adithyaakrishna** [comment]
Yep, on it @leecalcote

**Comment by leecalcote** [comment]
Thank you much.

**Comment by Deepansharora27** [comment]
I would like to work on this @vedant-kakde

**Comment by warunicorn19** [comment]
Please go ahead @Deepansharora27

**Comment by Deepansharora27** [comment]
Thanks @warunicorn19

**Comment by vedant-kakde** [comment]
Thanks @Deepansharora27 & @warunicorn19

**Comment by Deepansharora27** [comment]
Hi 
While working on this issue I am having a query that :
The Screenshot which is to be incorporated is present in the assets directory or do I need to include it explicitly ?

**Comment by adithyaakrishna** [comment]
@Deepansharora27 Thanks a lot man :)
I had completely forgot about this issue :/

**Comment by Deepansharora27** [comment]
@adithyaakrishna I have made a pull request for the same.
@debo19 has suggested some changes
So will be incorporating that
