### ISSUE TITLE
Incorrect resource URLs

### ISSUE THREAD

**Issue by king-11** [service-mesh-performance/service-mesh-performance#254]
**Description**

`unsubscribed` page uses a relative url when asking for css and js resources which point to `unsubscribed/assets/css/responsive.css`

**Expected Behavior**

The resource should point to `/assets/css/responsive.css`

**Screenshots**

![image](https://user-images.githubusercontent.com/52061363/136651231-8658d9de-9ee8-448b-a923-fd6f812fb593.png)

**Environment:**
 - OS: Manjaro
 - Browser: Brave
 - Version: 1.29.79-1
 - Device: Laptop

---
[Optional] **To Reproduce**
1. Go to https://smp-spec.io/unsubscribed/
2. Click on open the developer tools
3. Open the networks tab

**Comment by leecalcote** [comment]
@king-11 still something that you're working on?

**Comment by king-11** [comment]
@leecalcote sorry for the delay i will look at it this weekend 😄
