### ISSUE TITLE
Provide link to SMP blog on Medium on smp-spec.io site

### ISSUE THREAD

**Issue by sunkuranganath** [service-mesh-performance/service-mesh-performance#260]
Based on discussion in Slack, it was decided to provide a link to the following blog about SMP.
It would be good to provide this on smp-spec.io site.

Blog: https://sunkur.medium.com/5-things-to-know-about-service-mesh-performance-a8331765e995

**Comment by leecalcote** [comment]
@sunkuranganath what do you think? Does publishing the post under https://smp-spec.io/blog make sense?

**Comment by sunkuranganath** [comment]
@leecalcote  yes absolutely. Since the original blog talks about my perspective it might be of better influence to directly link to that. If you see that doesnt fit into the site, we can port the content over to a new page and mention at the end the source of the content. I am good with either methods.

**Comment by navendu-pottekkat** [comment]
@sunkuranganath Please create a new page and write your article there. We can add a canonical URL to your original post and mention that as well when we publish. This would ensure that we do not affect the SEO of the post and the website.

**Comment by leecalcote** [comment]
@sunkuranganath, new year, new attempt at this request?

**Comment by sunkuranganath** [comment]
Thanks for being patient. Will publish this shortly.
