### ISSUE TITLE
[UI]- Fix alignment of the content in the website

### ISSUE THREAD

**Issue by ghulamyazdani** [service-mesh-performance/service-mesh-performance#264]
**Description**

Content in the website is not center-aligned.
![image](https://user-images.githubusercontent.com/55938346/139545250-a7a5aa3f-5f47-4e49-b298-fb771a499358.png)

**Expected Behavior**

content should be center aligned . 
#### For ex.
![image](https://user-images.githubusercontent.com/55938346/139546899-9dade3f7-b2a0-4c5c-a294-4c238ae54f42.png)

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'https://smp-spec.io/'
2. Click on 'Check mobile view of the website from developer tools'
3. Scroll down to 'content of the website'

**Comment by ghulamyazdani** [comment]
@leecalcote I would like to fix this as well

**Comment by vedant-kakde** [comment]
Hey @ghulamyazdani I think Akshat is already working on this issue for aligning the website content. So this issue can be closed. Thanks.

**Comment by warunicorn19** [comment]
@vedant-kakde that issue lists some different issues, @ghulamyazdani you can go ahead with this.

**Comment by ghulamyazdani** [comment]
> Hey @ghulamyazdani I think Akshat is already working on this issue for aligning the website content. So this issue can be closed. Thanks.

Hey @vedant-kakde issue addressed by akshat is different that's why I am creating a new issue for content alignment

**Comment by vedant-kakde** [comment]
@ghulamyazdani yes got it. Go ahead 🚀
