### ISSUE TITLE
[Bug] Remove the unwanted "by" from the "MAIN" blog site.

### ISSUE THREAD

**Issue by Mr-DG-Wick** [service-mesh-performance/service-mesh-performance#275]
**Current State of the service-mesh-performance site**

The current blog site has an unwanted "by" word at the top. See this for reference: 

![Screenshot (1117)_LI](https://user-images.githubusercontent.com/81250703/142165589-280c2428-ccb0-4282-be18-34669f056548.jpg)

**Desired State of the service-mesh-performance site**

Restrict the "by" word only to specific blog pages, for example see [this](https://smp-spec.io/blog/spec/kubecon-cloudnativecon). We want the "by" word to only be at the specific pages and not on the main blog page.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by toth2000** [comment]
Looking into this.

**Comment by warunicorn19** [comment]
thank you @toth2000
