### ISSUE TITLE
[Site] Responsive issue: overlapping buttons

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#277]
**Description**
<img width="965" alt="Screen Shot 2021-11-19 at 5 24 37 PM" src="https://user-images.githubusercontent.com/7570704/142709914-fb34c124-d1e2-44d4-8452-1e32d282fc57.png">

**Expected Behavior**
These two buttons shouldn't overlap.

**Comment by king-11** [comment]
I would like to take this up

**Comment by sahilsuman933** [comment]
@leecalcote Can you please assign this task to me.

**Comment by leecalcote** [comment]
Oh, my goodness. I missed the messages here. @king-11 you're most welcome to pick this one up. Assuming that we've missed you on this one, I'll tag @sahilsuman933. Please do comment, though, if you'd still like to give this one a go.

**Comment by sahilsuman933** [comment]
@leecalcote Sure Sir. I would love to fix this issue :)
