### ISSUE TITLE
Update Slack.yml and add newcomer-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [service-mesh-performance/service-mesh-performance#289]
**Current Behavior**
Currently the slack.yml is outdated. Also there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Update slack.yml and add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the updated slack.yml file and the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

**Comment by leecalcote** [comment]
Thank you, @cpepper96 👍
