### ISSUE TITLE
SMP should measure CPU and memory usage of mesh resources

### ISSUE THREAD

**Issue by jbyers19** [service-mesh-performance/service-mesh-performance#292]
**Current Behavior**
Current SMP metrics are focused primarily on network performance: latency, RPS, etc.

**Desired Behavior**
CPU and memory performance should be measured in addition to network performance.

---

**Alternatives / Additional Context**
Network performance is a very important aspect of a service mesh, but CPU and memory usage are important as well. Users will be able to use this information when determining how large their cluster needs to be.

**Comment by gyohuangxin** [comment]
At this stage, what SMP can measure depends on the output of load-generators(ngihthawk, wrk2, fortio), and they are not good at measuring CPU and memory. 
We can extend our meshery-perf functions to get CPU, memory and other useful metrics from Prometheus API and return. Any comments? @leecalcote @navendu-pottekkat 

@sunkuranganath FYI. I know you're an expert in this.

**Comment by navendu-pottekkat** [comment]
Meshery does facilitate this to some extent that users can [use Meshery to deploy Prometheus and collect metrics](https://docs.meshery.io/functionality/performance-management) they want and display it on a Grafana dashboard while running performance benchmarks. But these are not captured in the spec and not in Meshery's test results.

Expanding the spec as this issue requests is a first step towards that. The spec does not need to limit itself to what Meshery can handle right now in my opinion.

Going forward with the implementation of [Nighthawk and its adaptive load control capabilities in Meshery](https://docs.google.com/document/d/1Qy_BpHXibTvL9daLTc5L4fjmr1F051ya0UYeghNUq_I/edit#heading=h.cxiuli7fu1z0), we look towards building pluggable interfaces for users to bring in their own metrics monitoring tool (like Prometheus).

So yes, updating the spec and a pluggable interface where users can bring in their own metrics plugin where Meshery will collect metrics like CPU and Memory use from it and add it to the test results, will be good to implement.

**Comment by gyohuangxin** [comment]
@navendu-pottekkat Can't agree anymore, SMP shouldn't be limited with Meshery capability. I'll work on it, thanks!

**Comment by gyohuangxin** [comment]
@jbyers19 @navendu-pottekkat I raised a PR to add CPU, Memory and Swap usage information in performance test result. I'm not sure if it meets real needs, can you have a review and  leave comments?
