### ISSUE TITLE
Refresh GitHub Issue Templates

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#293]
**Current Behavior**
The current template for feature request, bug, question, and website need to be updated (https://github.com/service-mesh-performance/service-mesh-performance/tree/master/.github/ISSUE_TEMPLATE).

**Desired Behavior**
Copy from Meshery and Meshery.io's issue templates, updating the templates in this repo with a very similar format.

**Comment by Ciggzy1312** [comment]
Hey @leecalcote I would like to give this a try

**Comment by leecalcote** [comment]
Thanks, @Ciggzy1312 !

**Comment by KerinPithawala** [comment]
Can I work on this issue?

**Comment by Ciggzy1312** [comment]
@KerinPithawala I am almost done with this :) 
@leecalcote I think the current site_update.md looks better than meshery.io's but if you still want me to alter it I will. Do let me know what you think

**Comment by leecalcote** [comment]
@KerinPithawala thanks for jumping in. Actually, the issue templates across all repos in the five orgs that we shepherd - https://discuss.layer5.io/t/layer5-community-now-spans-across-five-github-organizations/117. Please do.

**Comment by leecalcote** [comment]
@Ciggzy1312 ha! You're right. Let's flip-flop this request and have the meshery.io issue template updated.
