### ISSUE TITLE
Need validation for the Newsletter form

### ISSUE THREAD

**Issue by YashKamboj** [service-mesh-performance/service-mesh-performance#298]
#### Description

There is no validation of the input fields in the newsletter form .
#### Expected Behavior

should not proceed without any input
#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Vidyaa123** [comment]
Hi @YashKamboj, Can I work on this issue, please?

**Comment by YashKamboj** [comment]
Yeah!!, Go ahead 👍

**Comment by Vidyaa123** [comment]
👍

**Comment by Vidyaa123** [comment]
> @Vidyaa123 Yeah!!, Go ahead 👍

👍

**Comment by YashKamboj** [comment]
@Vidyaa123 you can check layer5io/getnighthawk#234 for reference, if you face any problem

**Comment by Vidyaa123** [comment]
> @Vidyaa123 you can check [layer5io/getnighthawk#234](https://github.com/layer5io/getnighthawk/pull/234) for reference, if you face any problem

I have completed and raised a PR for this issue.

**Comment by YashKamboj** [comment]
Oh, you forgot to connect the pr
