### ISSUE TITLE
SMP community information need to be updated

### ISSUE THREAD

**Issue by gyohuangxin** [service-mesh-performance/service-mesh-performance#308]
**Current State:**
Current community information is outdated, someone interested in SMP can't find out the latest status.

**Desired State:**
We need to update the meeting minutes link and zoom link: https://github.com/service-mesh-performance/service-mesh-performance/blob/master/README.md?plain=1#L19

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by gyohuangxin** [comment]
@leecalcote What do you think?

**Comment by gyohuangxin** [comment]
@leecalcote And can you add my name here? https://github.com/service-mesh-performance/service-mesh-performance/blob/master/MAINTAINERS.md

**Comment by leecalcote** [comment]
> @leecalcote What do you think?

Sounds great. Yes, let's have this info updated. 👍
