### ISSUE TITLE
Prevent overlapping of sidebar in Dashboard 

### ISSUE THREAD

**Issue by Abhijay007** [service-mesh-performance/service-mesh-performance#311]
#### Description

Right now the sidebar in the dashboard is overlapping the footer of the site

#### Expected Behavior

Try to prevent overlapping, if possible restrict the behavior of the sidebar above the footer only 

#### Screenshots

![image](https://user-images.githubusercontent.com/64387054/162040363-f8ebc4d4-572f-4d4a-bc9c-45f702a6bd1f.png)

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
#### [Optional] To Reproduce
1. Go to 'site and open dashboard '
2. Click on 'sidebar'
3. Scroll down to 'footer '
4. See it is overlapping 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
cc @asubedy

**Comment by asubedy** [comment]
Yes thank you @Abhijay007, I was going to fix it sneakily 😆

**Comment by Abhijay007** [comment]
> Yes thank you @Abhijay007, I was going to fix it sneakily 😆

Ya, @asubedy and let me know if you need any kind of assistance regarding Dashboard responsiveness in mobile devices or new features implementation :)

**Comment by Abhijay007** [comment]
> > Yes thank you @Abhijay007, I was going to fix it sneakily 😆
> 
> Ya, @asubedy and let me know if you need any kind of assistance regarding Dashboard responsiveness in mobile devices or new features implementation :)

one more thing that we may need to restrict the usage of the dashboard on mobile devices because I don't think it is accessible on that or maybe not compatible too, thoughts?

**Comment by asubedy** [comment]
> one more thing that we may need to restrict the usage of the dashboard on mobile devices because I don't think it is accessible on that or maybe not compatible too, thoughts?

@Abhijay007 well I don't think we can restrict usage, although it will look nice om a PC devices but still having responsiveness on a mobile device will still be a plus point. The graph visibility could be reduced on a mobile device but that shouldn't stop us to make a mobile compatible site.

**Comment by Akshit42-hue** [comment]
Hey @asubedy, @Abhijay007 Can I work on this issue

**Comment by asubedy** [comment]
Hi @Akshit42-hue , this issue is already a work in  progress.  I encourage you to look for other issues to contribute in the mean time. Thank you. 😄

**Comment by Akshit42-hue** [comment]
Ok, thanks for the update @asubedy :)

**Comment by leecalcote** [comment]
@asubedy who's working on the issue? Please update the Assignee.
