### ISSUE TITLE
Publication of MeshMark

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#323]
#### Current Behavior
Related to #227, MeshMark in its initial form has been defined.

#### Desired Behavior
Its definition should be published on amp-spec.io/meshmark

#### Acceptance Tests
1. This should include its formula and description of scoring system.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Abhijay007** [comment]
Hi @leecalcote do we need to make a separate page covering MeshMark?  I am a little confused as we already have this page here: https://smp-spec.io/blog/spec/meshmark-explained, would you please tell me what you mean by the "publication of MeshMark" and from where I can learn more about it.

**Comment by leecalcote** [comment]
Yes. - separate page. Materials for the page can be found in the ServiceMeshCon EU deck and the google doc on MeshMark.

**Comment by Abhijay007** [comment]
> Yes. - separate page. Materials for the page can be found in the ServiceMeshCon EU deck and the google doc on MeshMark.

Ok I will work on it
