### ISSUE TITLE
Website: Improve footer responsiveness

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#336]
#### Description
Currently:
<img width="1068" alt="Screen Shot 2022-05-18 at 1 10 40 PM" src="https://user-images.githubusercontent.com/7570704/169115124-eb10df57-16ee-43d7-84ea-4dff970a2224.png">

#### Expected Behavior
Breakpoints and column sizes should be adjusted to better fit browser width responsively.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Harshit-Dandriyal** [comment]
I can take this issue if no one is taking this issue in today :smile:

**Comment by gyohuangxin** [comment]
@Harshit-Dandriyal Thank you for taking this, please go ahead.

**Comment by neeraj-2** [comment]
Thinking to work on some small issues for having a good understanding of the project. Can I take it and create a PR for the same @gyohuangxin, @leecalcote?

**Comment by gyohuangxin** [comment]
@neeraj-2 Of course, it seems @Harshit-Dandriyal doesn't have updates so far. Please go ahead to take this and create a PR.

**Comment by leecalcote** [comment]
Excellent. 😀
