### ISSUE TITLE
Dashboard: reporting 404 when turning pages

### ISSUE THREAD

**Issue by gyohuangxin** [service-mesh-performance/service-mesh-performance#348]
#### Description

When I click the button below to turn to page 2, it will report 404 error.
![image](https://user-images.githubusercontent.com/42127654/182510759-69cd376a-ab9c-4ed6-99a2-3b8493504103.png)
![image](https://user-images.githubusercontent.com/42127654/182510789-79396b71-62fa-4c9e-8a99-97492bb790df.png)

**Comment by gyohuangxin** [comment]
@asubedy Can you take a look at this?

**Comment by asubedy** [comment]
Yikes 😱 ok I am taking a look.

**Comment by gyohuangxin** [comment]
@asubedy Thank you!

**Comment by gyohuangxin** [comment]
I have one more question, why are only 5 profiles shown in the dashboard? 
![image](https://user-images.githubusercontent.com/42127654/182518666-b63a95a8-5237-4633-9682-a5068dda3053.png)

We now have 12 profiles in the scheduled benchmark.
![image](https://user-images.githubusercontent.com/42127654/182518893-e3c71589-f51e-408c-a1ed-00f4ba7d360e.png)

**Comment by asubedy** [comment]
As stated on the slack. The performance profile which don't hbe any result re hidden on the frontend. Removing them we are left with only five profiles.

**Comment by gyohuangxin** [comment]
@asubedy Any updates?
