### ISSUE TITLE
Adaptive Load Controller

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#350]
#### Current Behavior
The goal of an adaptive load controller is to determine the maximum load a system can sustain.

The maximum load is usually defined by the maximum requests per second (rps) the system can handle. The metrics (CPU usage, latency etc) collected from the system under test are the constraints we provide to judge whether a system under test (SUT) is sustaining the load.

A use-case that fits very well is be the ability to use it to run performance tests on a schedule and track the maximum load a system can handle over time. This could give insights to performance improvements or degradations.

#### Desired Behavior
See [design specification](https://docs.google.com/document/d/1Qy_BpHXibTvL9daLTc5L4fjmr1F051ya0UYeghNUq_I/edit?usp=sharing)

#### Implementation
1. Nighthawk as an Externalized Meshery Component
1. Add adaptive load control capability to Meshery server.
1. Expose this functionality in Meshery UI and CLI.
1. Make this functionality extensible through plugins and extensions.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by zeel-pathak** [comment]
Hey @leecalcote, I would love to work on this issue under LFX Mentorship.

Apart from applying on LFX, is there anything else I should do to increase my chances of selection?

Would love to work with such an amazing community.

**Comment by zeel-pathak** [comment]
Hey @leecalcote, submitted my application and can't wait to work on this project. Looking forward to work as mentee and hope to get selected ☺️

**Comment by RajGM** [comment]
Hi @leecalcote 
Does that mean we are implementing this to build analytics that would be used later to increase performance or decrease cost?

**Comment by leecalcote** [comment]
> Hi @leecalcote
> Does that mean we are implementing this to build analytics that would be used later to increase performance or decrease cost?

To give control over both cost and performance.

**Comment by leecalcote** [comment]
Given last year's success, we'll be opening up a new issue to track another open internship on this subject.
