### ISSUE TITLE
[bug] Trailing "/" not redirecting to Dashboard

### ISSUE THREAD

**Issue by theBeginner86** [service-mesh-performance/service-mesh-performance#357]
#### Description

Currently, `https://smp-spec.io/dashboard/` doesn't redirect to `https://smp-spec.io/dashboard` and leads to 404 page.
This edge case should be accounted for and users should be redirected to the correct page.

Error:
<img width="1319" alt="Screenshot 2022-10-27 at 9 54 37 PM" src="https://user-images.githubusercontent.com/73700530/198345883-17c56aed-0b4c-4a19-add8-7a5cc40cb014.png">

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by theBeginner86** [comment]
// @asubedy

**Comment by Adi-ty** [comment]
@theBeginner86 I wanted to contribute on this issue just wasn't able to find where the code for the website and routing b/w pages is written exactly can you guide me here

**Comment by yash37158** [comment]
Hey I would like to work on this issue @theBeginner86 @nicholasjackson

**Comment by theBeginner86** [comment]
> Hey I would like to work on this issue @theBeginner86 @nicholasjackson 
> 

Thanks @yash37158 for taking this up 🚀

**Comment by theBeginner86** [comment]
@yash37158 any progress to share?
Lets discuss this in today's website meeting. // @Chadha93 


Would you kindly add this as an agenda item? https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by Chadha93** [comment]
> @yash37158 any progress to share? Lets discuss this in today's Website meeting. // @Chadha93
> 
> Would you kindly add this as an agenda item? [docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

Thanks for making a call here @theBeginner86. I think @yash37158 is no longer working on this issue. I'll ask for a new volunteer  in today's call.

**Comment by theBeginner86** [comment]
We are okay to close this issue.

@asubedy just helped us 😎
