### ISSUE TITLE
Replace the Logo of Layer5 with Service Mesh Performance in config.yml workflow

### ISSUE THREAD

**Issue by anshgoyalevil** [service-mesh-performance/service-mesh-performance#375]
### Description

Currently, we are using the Logo of Layer5 instead of Service Mesh Performance. This repository is under the organization Service Mesh Performance, so, there should be the image of Service Mesh Performance.

**How to resolve this?**
- Go to .github and replace this welcome image with the new one: 

![Service-Mesh-Performance-celebration](https://user-images.githubusercontent.com/94157520/231488336-5064316c-01d7-41e3-bc90-2b0572c1d089.png)

- Download this image, and upload with the correct name for future reference. The name of the image should be Service-Mesh-Performance-celebration.
- After uploading the image, and removing the previous image, go to .github/config.yml folder and update the reference to previous image to the new image in the following part:

```
  Thanks for your contribution to the Layer5 community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/service-mesh-performance/service-mesh-performance-specification/master/.github/welcome/Layer5-celebration.png)
 &nbsp;
 &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9;   :star: Please [star the project](../stargazers) if you have yet to do so.
```
- That's it.

-----

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by SumantxD** [comment]
@anshgoyalevil I would like to work on this issue oculd you assign it to me
