### ISSUE TITLE
[Dashboard] "SMP" as Service Mesh value

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-performance/service-mesh-performance#385]
#### Description
<img width="605" alt="Screenshot 2023-06-28 at 9 52 07 AM" src="https://github.com/service-mesh-performance/service-mesh-performance/assets/7570704/285f7541-c755-49f7-8521-706780cc1064">

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by asubedy** [comment]
Fixed
