### ISSUE TITLE
Update Twitter Logo to X(New logo)

### ISSUE THREAD

**Issue by aaronsgeorge** [service-mesh-performance/service-mesh-performance#397]
#### Description

Current State of the https://smp-spec.io/
![twitter](https://github.com/service-mesh-performance/service-mesh-performance/assets/92575127/09ce1390-0430-4f3a-921a-fd4eac5983f4)

#### Expected Behavior

Update Twitter logo to X
![newtwitter](https://github.com/service-mesh-performance/service-mesh-performance/assets/92575127/19380085-dc40-4622-99eb-170b18ba7f71)

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by karpMagikarp** [comment]
I want to solve this issue

**Comment by Savio629** [comment]
@Chadha93 @vishalvivekm

**Comment by vishalsingh2972** [comment]
can I give this a try if its open?

**Comment by Chadha93** [comment]
Thanks for volunteering everyone, assigning in chronological order.

**Comment by thisiskaransgit** [comment]
Hey @karpMagikarp, please signal if you are actively working on this issue. if you're not we'll assign it to any of the other volunteers.

**Comment by karpMagikarp** [comment]
> Hey @karpMagikarp, please signal if you are actively working on this issue. if you're not we'll assign it to any of the other volunteers.

Hey, sorry for the late reply. I've been trying to solve the problem for quite some time. To apply the new Twitter x icon to the website I would have to update Font Awesome to version 6 from version 5.
Do I update it on my own or wait for an update from your side.
