### ISSUE TITLE
Discuss forum doesnt redirect

### ISSUE THREAD

**Issue by Ghat0tkach** [service-mesh-performance/service-mesh-performance#400]
#### Description

Discuss forum doesnt redirect to discuss.layer5.io instead it leads to group mailing list
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/59855919/7e5ba5bb-c87b-4488-b58f-1f3ca389ba84)

#### Expected Behavior

It should redirect to https://discuss.layer5.io/
#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by abhijeetgauravm** [comment]
I would like to fix it!

**Comment by Layak-Ali** [comment]
@Ghat0tkach can you assign me this issue? No one has been assigned yet

**Comment by Layak-Ali** [comment]
@leecalcote can you assign me this issue?? I have only successfully completed 2 PRs. @Ghat0tkach isnt replying too

**Comment by leecalcote** [comment]
Thank you, gents. Assigning in chronological order...

**Comment by Ghat0tkach** [comment]
@abhijeetgauravm any updates?

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm any updates?

looking into it @Ghat0tkach

**Comment by Layak-Ali** [comment]
@abhijeetgauravm if you are busy you can assign me the task.

**Comment by abhijeetgauravm** [comment]
Go for it @Layak-Ali 🚀... @Ghat0tkach please assign @Layak-Ali for this !

**Comment by hemantmm** [comment]
Hi, @leecalcote fixed this issue and sent PR.

**Comment by Layak-Ali** [comment]
but @Ghat0tkach said that i should first get assigned before submitting my PR when i submitted my PR before getting assigned. I hope you assign me this issue. @leecalcote

**Comment by abhijeetgauravm** [comment]
> Hi, @leecalcote fixed this issue and sent PR.

hey @hemantmm Just ask for assignment before making direct PR.

**Comment by Ghat0tkach** [comment]
@Layak-Ali  , I already said please dont delay creating a PR  😊.  https://github.com/layer5io/layer5/issues/4798#issuecomment-1703364153

@hemantmm  , We really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first . Please take care of it from near future


Since @hemantmm already created a working PR , please review it @Layak-Ali

**Comment by Layak-Ali** [comment]
@Ghat0tkach i think his PR has no issues but i don't think he signed commits. The issue is solved though.
