### ISSUE TITLE
Dashboard Page: Non-Responsive Performance Profile Table in Result Display 

### ISSUE THREAD

**Issue by mayurjadhav2002** [service-mesh-performance/service-mesh-performance#401]
### Description

The issue on the dashboard page the performance profile table which shows result table is not responsive. take a look at the below screenshots. 

On **mobile**, it is just showing the profile and endpoints. It is not horizontally scrollable to see other information. 

### Screenshots

**On Desktop**
![scrnli_15_08_2023_00-58-57](https://github.com/service-mesh-performance/service-mesh-performance/assets/63432459/fd51fd47-7477-4d7f-8740-51fffcfdc2ac)

**On Mobile or Small screen devices**
![scrnli_15_08_2023_01-01-06](https://github.com/service-mesh-performance/service-mesh-performance/assets/63432459/4ef2ab50-2e29-41d1-9326-e5566ed889e3)

#### Expected Behavior

the table should be horizontally scrollable so the user can see the other two columns.

#### Environment:
 - OS: [Android, IOS]
 - Browser: [e.g. Chrome]

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Adi-ty** [comment]
Can I work on this

**Comment by abhijeetgauravm** [comment]
> Can I work on this

He has made PR . Can anyone assign him @asubedy @gyohuangxin ?
