### ISSUE TITLE
[Docs] Broken Link of Meshery Documentation Build and Release Page in service-mesh-performance

### ISSUE THREAD

**Issue by Mohiit70** [service-mesh-performance/service-mesh-performance#403]
**Current State:**
The link in question is: https://docs.meshery.io/project/build-and-release. Clicking this link leads to a 404 error page with the message

![Screenshot layer](https://github.com/service-mesh-performance/service-mesh-performance/assets/120316966/284e2674-b678-4930-a650-9b456a6be4eb)

![Screenshot 2023-08-20 185120](https://github.com/service-mesh-performance/service-mesh-performance/assets/120316966/348656d3-8f00-464c-94ff-874a6a4baa42)

**Desired State:**
Clicking the link should take users to the correct documentation page on Meshery's build and release information.
---

**Contributor Resources**

- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Mohiit70** [comment]
Please assign this issue to me.

**Comment by Ghat0tkach** [comment]
@Mohiit70 , this issue is related to ,meshery/meshery repository

**Comment by Mohiit70** [comment]
> @Mohiit70 , this issue is related to ,meshery/meshery repository

got it
