### ISSUE TITLE
Fixing Installation issue

### ISSUE THREAD

**Issue by vaibhav-xp** [service-mesh-performance/service-mesh-performance#407]
#### Description
While running commands `make site` and `make build`, encountered an issue:
```bash
$ make site
cd docs; \        
        make site;
make[1]: Entering directory `D:/Journey/service-mesh-performance/docs'
bundle exec jekyll serve --drafts --livereload
Could not find nokogiri-1.13.9, jekyll-coffeescript-2.0.0, webrick-1.7.0, jekyll-4.2.1, html-pipeline-2.14.0, mini_portile2-2.8.0, racc-1.6.0, coffee-script-source-1.12.2, addressable-2.8.0, em-websocket-0.5.2, i18n-1.8.10, jekyll-sass-converter-2.1.0, kramdown-2.3.1, liquid-4.0.3, rouge-3.26.1, terminal-table-2.0.0, activesupport-6.1.4.1, execjs-2.7.0, public_suffix-4.0.6, http_parser.rb-0.6.0, concurrent-ruby-1.1.9, sassc-2.4.0, listen-3.7.0, minitest-5.14.4, tzinfo-2.0.4, zeitwerk-2.4.2, ffi-1.15.4, rb-fsevent-0.11.0 in locally installed gems
Run `bundle install` to install missing gems.
make[1]: *** [site] Error 7
make[1]: Leaving directory `D:/Journey/service-mesh-performance/docs'
make: *** [site] Error 2
``` 

#### Expected Behavior
[Solution](https://discuss.layer5.io/t/service-mesh-performance-installation-issue/3489/4?u=vaibhav.maurya)

#### Enviroment:
 - OS: Mac, Window, Linux
 - Browser: Chrome, Safari
 - Version:
 - Device:

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by vaibhav-xt** [comment]
I would like to work on this issue.
