### ISSUE TITLE
Yaml Code Syntax Error 

### ISSUE THREAD

**Issue by akhilender-bongirwar** [service-mesh-performance/service-mesh-performance#409]
#### To Reproduce 
- Navigate to `https://smp-spec.io/blog/spec/pipelining-service-mesh-specifications`  
- Scroll down to "Using Meshery’s Service Mesh Performance GitHub Action"
- See syntax error  in the  yaml code. 

### Screenshot  
![Screenshot 2023-09-11 013556](https://github.com/service-mesh-performance/service-mesh-performance/assets/112749383/4da3e294-85b0-4c59-a92c-258ae2bbc1f0)

#### Expected Behavior
- The indentation for the name is not correct. It should be corrected to have a valid yaml syntax.

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.

**Comment by gyohuangxin** [comment]
@akhilender-bongirwar Thanks!
