### ISSUE TITLE
Extra space on right-side in Mobile view

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [service-mesh-performance/service-mesh-performance#425]
#### Description
In Mobile-view navbar is good but whole HTML body (specifically in Mobile-L 425px), due to image overflow issue, has an extra space on the right side of screen

#### Expected Behavior
There should be no extra space.

#### Screenshots
![Screenshot from 2024-05-31 08-15-02](https://github.com/service-mesh-performance/service-mesh-performance/assets/54661456/1ac53137-943d-460d-943c-fb8e09d35559)

#### Enviroment:
 - OS: Ubuntu
 - Browser: Chrome
 - Version: [e.g. 22]
 - Device: laptop

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by gyohuangxin** [comment]
@Muhammed-Moinuddin Thanks for creating this issue, are you interested in sloving it?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Thanks for creating this issue, are you interested in sloving it?

Yes, I'll love to work on it. Kindly assign it to me.

**Comment by gyohuangxin** [comment]
@Muhammed-Moinuddin Great 👍
