### ISSUE TITLE
Cards and their description are not aligned 

### ISSUE THREAD

**Issue by upsaurav12** [service-mesh-performance/service-mesh-performance#428]
#### Description
Currently the Description containers for cards are not properly aligned with their respective cards container specifically from ``400px >`` to ``<=600px`` 

Also at break point ``634px`` Card's title is overflowing 
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/8f05cd02-a00e-47dd-b14a-7c231f4051d8)

#### Expected Behavior
They should be properly aligned with their respective cards just like other breakpoints
**Such as**
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/730157fa-dba6-4bbc-ac46-99a5aa2ff42a)

#### Screenshots

**Here are Screen Shots** 
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/6359ab85-edbd-41e3-82d3-84e6cb3c9600)
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/fa685021-3f62-4fee-8135-5de058598c0f)

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
#### [Optional] Additional Context
**Kindly assign me this issue**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Muhammed-Moinuddin** [comment]
@gyohuangxin @leecalcote. Kindly check it

**Comment by gyohuangxin** [comment]
@upsaurav12 Are you also interested to taking this issue?

**Comment by upsaurav12** [comment]
yes i am interested i solved the problem this is how it is looking 

Uploading cinnamon-2024-07-09T2055200530.mp4…

dont know about the width of caption container but i guess everything is fine

**Comment by vaishnaviadhau** [comment]
@Muhammed-Moinuddin is this issue still open?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin is this issue still open? if it is then I would like to work on it

Not yet. One of @upsaurav12 is solving it

**Comment by upsaurav12** [comment]
@Muhammed-Moinuddin i have almost solved it but waiting to get assigned😅

**Comment by gyohuangxin** [comment]
@upsaurav12 Sorry for omitting.

**Comment by upsaurav12** [comment]
It is ok

**Comment by Ashparshp** [comment]
@upsaurav12 Any luck? Also, if you don't mind, could you kindly mention the steps to reproduce the issue along with the URL?

**Comment by upsaurav12** [comment]
1. https://smp-spec.io/
2. See cards section
3. change the width
