### ISSUE TITLE
Pipelining services mesh performance blog page is not responsive 

### ISSUE THREAD

**Issue by upsaurav12** [service-mesh-performance/service-mesh-performance#429]
#### Description
Pipelining services mesh performance the is not responsive like the nav bar is overflowing horizontally , containers are not algined they are also overflowing from their respective parent's container
Here is the video 

https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/2d2a4646-7a38-4ea3-a64f-556afe5a431b

#### Expected Behavior

They should be responsive just like other blog pages they all are responsive for smaller width 

#### Screenshots
![image](https://github.com/service-mesh-performance/service-mesh-performance/assets/116784047/df40c4a7-9156-494d-a328-f22340c1d931)

#### Enviroment:
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by upsaurav12** [comment]
Kindly assign me this issue

**Comment by gyohuangxin** [comment]
@upsaurav12 Thanks for taking this issue.

**Comment by upsaurav12** [comment]
Hi @gyohuangxin i am very new in this codespace i have not much idea about setup

**Comment by Muhammed-Moinuddin** [comment]
> Hi @gyohuangxin i am very new in this codespace i have not much idea about setup

Kindly check CONTRIBUTING.md (setup procedure is there) and I'll suggest you to join Layer5 slack channel as well.

**Comment by upsaurav12** [comment]
This is issue can be fix by changing width of ``cards`` at smaller width but the problem is that this will apply on every element class named as ``card`` so can i make a saparate name that will apply specifically for ``blogs page``or the ``pipeline service mesh performace page`` 
![image](https://github.com/user-attachments/assets/b52fabc1-bfa4-44f0-9c6b-f2dc5780ba91)

**Comment by gyohuangxin** [comment]
@Muhammed-Moinuddin Sure, please go ahead and raise a PR.

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Sure, please go ahead and raise a PR.

@gyohuangxin you tagged a wrong guy😃

**Comment by gyohuangxin** [comment]
My fault 😂
