### ISSUE TITLE
Fixing CI Piplines

### ISSUE THREAD

**Issue by gyohuangxin** [service-mesh-performance/service-mesh-performance#435]
Currently, there are some issues in CI piplines. We need to fix them and delete unneccessary piplines..

**Comment by yashkhandelwal123** [comment]
Hi, i want to work on this issue. how can I start ?

**Comment by lekaf974** [comment]
@gyohuangxin can you share link to issues observed so I can investigate ?

**Comment by gyohuangxin** [comment]
@lekaf974 @yashkhandelwal123 Thanks for working on this, I think each of you can create a draft PR so that you can see the failed CI piplines and investigate to how to fix.

For example: https://github.com/service-mesh-performance/service-mesh-performance/pull/437

**Comment by lekaf974** [comment]
@gyohuangxin started a PR, could you allow the test running

**Comment by gyohuangxin** [comment]
@lekaf974  Done
